"""inicial

Revision ID: 9c0168a66617
Revises: 
Create Date: 2026-10-07 16:12:16.359778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9c0168a66617'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tiendas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('ciudad', sa.String(length=120), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('nombre_completo', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=100), nullable=False),
    sa.Column('tienda_id', sa.Integer(), nullable=False),
    sa.Column('rol', sa.Enum('ADMIN', 'GERENTE', 'EMPLEADO', 'AUDITOR', name='rol_usuario'), nullable=True),
    sa.Column('estado', sa.Enum('PENDIENTE', 'ACTIVO', 'DESACTIVADO', name='estado_usuario'), server_default='PENDIENTE', nullable=False),
    sa.Column('intentos_fallidos', sa.Integer(), server_default='0', nullable=False),
    sa.Column('bloqueado_hasta', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mfa_secreto_cifrado', sa.String(), nullable=True),
    sa.Column('mfa_activo', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('mfa_ultimo_contador', sa.Integer(), nullable=True),
    sa.Column('token_version', sa.Integer(), server_default='0', nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("estado = 'PENDIENTE' OR rol IS NOT NULL", name='ck_usuarios_rol_si_no_pendiente'),
    sa.ForeignKeyConstraint(['tienda_id'], ['tiendas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('email_intentado', sa.String(length=254), nullable=True),
    sa.Column('accion', sa.String(length=50), nullable=False),
    sa.Column('recurso', sa.String(length=50), nullable=True),
    sa.Column('recurso_id', sa.String(length=50), nullable=True),
    sa.Column('detalle', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('desafios_mfa',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('intentos', sa.Integer(), server_default='0', nullable=False),
    sa.Column('expira_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('usado', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('identidades_sociales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('proveedor', sa.Enum('GOOGLE', 'GITHUB', name='proveedor_social'), nullable=False),
    sa.Column('proveedor_uid', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('proveedor', 'proveedor_uid', name='uq_identidad_social_proveedor_uid')
    )
    op.create_table('productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tienda_id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=40), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('actualizado_por', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("nombre <> ''", name='ck_productos_nombre_no_vacio'),
    sa.CheckConstraint('precio >= 0', name='ck_productos_precio_no_negativo'),
    sa.CheckConstraint('stock >= 0', name='ck_productos_stock_no_negativo'),
    sa.ForeignKeyConstraint(['actualizado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['tienda_id'], ['tiendas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tienda_id', 'sku', name='uq_productos_tienda_sku')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('productos')
    op.drop_table('identidades_sociales')
    op.drop_table('desafios_mfa')
    op.drop_table('auditoria')
    op.drop_table('usuarios')
    op.drop_table('tiendas')
    # ### end Alembic commands ###
